### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ahmad-Mtr** [Ahmad-Mtr/CS254#1]
you can contribute them btw

- [x]  validate
- [x] setLayout(LayoutManager mgr), check _assignment1_
- [x] setBackground
- [x] setPreferredSize(Dimension d)
- [x] ColorPanel (basically `JPanel` with a constr. color)
- [x] FlowLayout
- [x] BorderLayout
- [x] GridLayout
- [x] setHgap()
- [x] setVgap()
- [x] LayoutFrame
- [x] common Component Properties
- [x] Events & Listeners
- [x] ActionEvents
- [ ] Graphics - Canvas
- [x] Graphics Methods
- [x] Screen Parameters
- [x] Graphics2D

- [x] JButton
- [x] JLabel
- [x] JTextField
- [x] JPasswordField
- [x] JOptionPane
